### ISSUE TITLE
.gd script conversion

### ISSUE THREAD

**Issue by DigitalN8m4r3** [thelastflapjack/all_alone#1]
while it is a pretty good starting point for a wave shooter, it feels somewhat overkill
would there be a chance to see this converted to .gd

**Comment by teeeece** [comment]
Maybe, but not for this 3.5 version. I am planning on the next version of this project (or some descendant of this project) to be made in godot 4 and was considering trying out GDScript 2.0 for this. I'm not sure when that would be.
